### ISSUE TITLE
Code is obfuscated

### ISSUE THREAD

**Issue by tcort** [guo-yu/awk#2]
There are no comments, the variable names are 1 letter, and the function names are 2 letters. It's open source, but the source is completely unreadable....

Example: https://github.com/turingou/awk/blob/master/libs/awk.js#L236

Can you post a non-obfuscated version please?

**Comment by guo-yu** [comment]
This project is a Node wrapper of `WebAwk`, please move to WebAwk to read source code: https://github.com/agordon/webawk
