### ISSUE TITLE
Writing output to a file

### ISSUE THREAD

**Issue by Werner0** [guo-yu/awk#3]
Hi @guo-yu 

What is the best way to write to a file using this awk package?

Adding the following command to the .awk file doesn't work:

```
$3 ~ "^rs" {print $3} > snp.txt
```

And none of the five properties of the result object seem to contain the awk output.

**Comment by Werner0** [comment]
The awk output can be captured using the [intercept-stdout](https://www.npmjs.com/package/intercept-stdout) node package. Here's the code:

```
var intercept = require("intercept-stdout");
var captured_text = "";
var unhook_intercept = intercept(function(txt) {
    captured_text += txt;
    });
awk(awkscript, data);
unhook_intercept();
```

**Comment by ai-chen2050** [comment]
@Werner0  **It works, Thx u, guy !**
